# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '百思不得姐' do
pod 'SDWebImage', '~>3.7'
pod 'SVProgressHUD'
pod 'AFNetworking', '~> 3.0'
pod 'MJExtension'
end

target '百思不得姐Tests' do

end

target '百思不得姐UITests' do

end

